server:
  port: 8097

spring:
  cloud:
    gateway:
      routes:
      - id: position_Module
        uri: http://192.168.1.29:3000/
        predicates:
        - Path=/intervPosition/**
      - id: employee_Module
        uri: http://192.168.1.29:3000/
        predicates:
        - Path=/employee/**        
                
        
  